Add Syntax Highlighting Change
magicsword-io/sigconverter.io pull request #37
Opened 2024-02-21 05:30 UTC by signus

Adds the ability to modify the DOM to change the PrismJS class utilized in the `query-code` block to update with the new class and remove the previously used class prior to adding the new one. This can help to ease formatting for visibilty as well as promote syntax definitions for the other target query languages.

Additionally this adds the external source for `prism-kusto.min.js` and `prism-sql.min.js` whereby the default language select for all other languages should be SQL as most target languages are rather SQL-like.

In the future this mechanism can be improved upon to include more languages as well as to add an Enum to map the target languages to the specific PrismJS class name.

2024-02-23 10:45 UTC, M3NIX commented
@signus Thank you for the pull request! I really do like the idea.
Instead of using a big switch statement I would suggest that we use a simple javascript object with the backend as keys and the language as values. If the backend is not found as a key we set a default language.

So something like that:
```js
let backend = getSelectValue("select-backend");
let language = "";
let prev_language = "";
let default_language = "language-sql"

// ... code to find the previous language

const languageMap = {
  "azure" : "language-kusto",
  "ibm-qradar-aql": "language-sql",
  "microsoft365defender": "language-kusto",
  "splunk": "language-splunk-spl",
  "qradar": "language-sql"
};

language = languageMap[backend] ? languageMap[backend] : default_language;
```

2024-02-23 10:47 UTC, M3NIX requested changes
adjust switch statement as suggested

2024-02-23 16:41 UTC, signus commented
Much appreciate the feedback! The switch statement was not desired, so thank you for helping to speed up that adjustment!

2024-03-06 12:39 UTC, M3NIX approved these changes

2024-03-06 12:41 UTC, merged